apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app:1.0.0-38
  template:
    metadata:
      labels:
        app: nodejs-app:1.0.0-38
    spec:
      containers:
        - name: nodejs-app:1.0.0-38
          image: khaoulaabdessamad/nodejs-app:1.0.0-38
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
